name: Deploy
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to EC2
      env:
        EC2_HOST: 35.154.133.178  # Replace with your Elastic IP
        EC2_USER: ubuntu
        EC2_KEY: ${{ secrets.EC2_KEY }}
      run: |
        echo "$EC2_KEY" > key.pem
        chmod 600 key.pem
        ssh -i key.pem $EC2_USER@$EC2_HOST "bash /var/www/my-website/scripts/deploy.sh"

        