name: Deploy

on:
  push:
    branches: [master]  # Use your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to EC2
        env:
          EC2_HOST: 13.126.9.71  # Replace with your EC2 IP
          EC2_USER: ubuntu
          EC2_KEY: ${{ secrets.EC2_SSH_KEY }}  # Ensure the secret exists
        run: |
          echo "$EC2_KEY" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST "bash /home/ubuntu/deploy.sh"
